# Generated by Django 5.0.6 on 2024-05-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=100)),
                ('career_descirption', models.CharField(max_length=250)),
                ('career_blog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cheatsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheat_name', models.CharField(max_length=100, unique=True)),
                ('cheat_blog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=100)),
                ('note_subject', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(max_length=250)),
                ('note_blog', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
