# Generated by Django 5.0.6 on 2024-05-16 07:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hopsstar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='cheatsheet',
            name='cheat_blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_blog',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
