# Generated by Django 5.0.6 on 2024-09-02 09:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hopsstar_app', '0002_alter_career_career_blog_alter_cheatsheet_cheat_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_campu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_college_name', models.CharField(max_length=250)),
                ('ad_university_name', models.CharField(max_length=100)),
                ('ad_affliation', models.CharField(max_length=100)),
                ('ad_rank', models.CharField(max_length=100)),
                ('ad_link', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ad_Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_career_head', models.CharField(max_length=250)),
                ('ad_career_link', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ad_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_note_head', models.CharField(max_length=250)),
                ('ad_note_link', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Campu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=250)),
                ('university_name', models.CharField(max_length=100)),
                ('affliation', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('campus_blog', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='contactbutton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=100)),
                ('whatsapp_link', models.URLField(max_length=300)),
                ('telegram_link', models.URLField(max_length=300)),
                ('youtube_link', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cookiespolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies_content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Privacypolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Termsandconditon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
