# Generated by Django 5.0.6 on 2024-09-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hopsstar_app', '0003_ad_campu_ad_career_ad_note_campu_contactbutton_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactbutton',
        ),
    ]
