# Generated by Django 5.0.6 on 2024-09-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hopsstar_app', '0006_delete_contactbutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactbutton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=100)),
                ('whatsapp_link', models.URLField(max_length=300)),
                ('telegram_link', models.URLField(max_length=300)),
                ('youtube_link', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
            ],
        ),
    ]
