"""
Django settings for Hopsstar_engine project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m=km3y87kwypc0my-=q%*v&c8deq&00=@*x_wjk709^k987cp_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['hopelism', 'www.hopelism.com', '145.223.21.101', 'hopelism.com']


CSRF_TRUSTED_ORIGINS = [
    'https://hopelism.com',
    'https://www.hopelism.com',
    'http://hopelism.com',  # Include HTTP as well
    'http://www.hopelism.com'  # Include HTTP as well
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',
    'admin_honeypot',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'Hopsstar_app',
    'pwa',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'ckeditor',
    'ckeditor_uploader',
    
       
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'axes.middleware.AxesMiddleware', 
]



ROOT_URLCONF = 'Hopsstar_engine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'Hopsstar_engine.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hopsstar__db',
        'USER': 'hopsstar_postgres',
        'PASSWORD': 'kQSxqhfqrylooJB',
        'HOST': 'localhost',
        'PORT': '5432'
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'static')
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static','js', 'serviceworker.js')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'contacthopsstar@gmail.com'
EMAIL_HOST_PASSWORD = 'vdiq kdoh xbis gmct'


SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDER = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'METHOD': 'oauth2',  # Set to 'js_sdk' to use the Facebook connect SDK
        #'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        #'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=30)

PWA_APP_NAME = 'Hopelism'
PWA_APP_DESCRIPTION = "My app description"
PWA_APP_THEME_COLOR = '#ffffff'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = '#ffffff'
PWA_APP_ICONS = [
    {
      'src': '/static/images/Hopelismlogo48.png',
      'sizes': '48x48',
    },
    {
      'src': '/static/images/Hopelismlogo72.png',
      'sizes': '72x72',
    },
    {
      'src': '/static/images/Hopelismlogo96.png',
      'sizes': '96x96',
    },
    {
      'src': '/static/images/Hopelismlogo144.png',
      'sizes': '144x144',
    },
    {
      'src': '/static/images/Hopelismlogo192.png',
      'sizes': '192x192',
    },
    {
      'src': '/static/images/Hopelismlogo512.png',
      'sizes': '512x512',
    }
]
PWA_APP_ICONS_APPLE = [
    {
      'src': '/static/images/Hopelismlogo60.png',
      'sizes': '60x60',
    },
    {
      'src': '/static/images/Hopelismlogo76.png',
      'sizes': '76x76',
    },
    {
      'src': '/static/images/Hopelismlogo120.png',
      'sizes': '120x120',
    },
    {
      'src': '/static/images/Hopelismlogo152.png',
      'sizes': '152x152',
    },
    {
      'src': '/static/images/Hopelismlogo167.png',
      'sizes': '167x167',
    },
    {
      'src': '/static/images/Hopelismlogo180.png',
      'sizes': '180x180',
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/images/splash-200x320.png',
        'media': '(device-width: 200px) and (device-height: 320px) and (-webkit-device-pixel-ratio: 0.75)'
    },
    {
        'src': '/static/images/splash-320x480.png',
        'media': '(device-width: 320px) and (device-height: 480px) and (-webkit-device-pixel-ratio: 1)'
    },
    {
        'src': '/static/images/splash-480x800.png',
        'media': '(device-width: 480px) and (device-height: 800px) and (-webkit-device-pixel-ratio: 1.5)'
    },
    {
        'src': '/static/images/splash-720x1280.png',
        'media': '(device-width: 720px) and (device-height: 1280px) and (-webkit-device-pixel-ratio: 2)'
    },
    {
        'src': '/static/images/splash-960x1600.png',
        'media': '(device-width: 960px) and (device-height: 1600px) and (-webkit-device-pixel-ratio: 2.5)'
    },
    {
        'src': '/static/images/splash-1280x1920.png',
        'media': '(device-width: 1280px) and (device-height: 1920px) and (-webkit-device-pixel-ratio: 3)'
    },
    {
        'src': '/static/images/splash-1440x2560.png',
        'media': '(device-width: 1440px) and (device-height: 2560px) and (-webkit-device-pixel-ratio: 3.5)'
    },
    {
        'src': '/static/images/splash-750x1334.png',
        'media': '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)'
    },
    {
        'src': '/static/images/splash-828x1792.png',
        'media': '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)'
    },
    {
        'src': '/static/images/splash-1242x2688.png',
        'media': '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)'
    },
    {
        'src': '/static/images/splash-1125x2436.png',
        'media': '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)'
    },
    {
        'src': '/static/images/splash-1536x2047.png',
        'media': '(min-device-width: 768px) and (min-device-height: 1024px) and (-webkit-device-pixel-ratio: 2)'
    },
    {
        'src': '/static/images/splash-1668x2388.png',
        'media': '(min-device-width: 834px) and (min-device-height: 1194px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'


SILENCED_SYSTEM_CHECKS = ["ckeditor.W001"]



